# Build-script for the aircraft a380x-experimental branch
# Builds the A32NX and the A380X and uploads them to the CloudFlare CDN

name: a380x-experimental
on:
  push:
    branches:
      - a380x-experimental

jobs:
  build_a32nx:
    name: Build and deploy A32NX
    # Prevent running this on forks
    if: github.repository_owner == 'flybywiresim'
    runs-on: ubuntu-latest
    env:
      FBW_PRODUCTION_BUILD: 1
      A32NX_INSTRUMENTS_BUILD_WORKERS: 2
      BUILD_DIR_NAME: a380x-experimental-a32nx
      AIRCRAFT_PROJECT_PREFIX: a32nx
      AIRCRAFT_VARIANT: a320-251n
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Create .env file
        run: |
          echo FBW_PRODUCTION_BUILD=1 >> fbw-a32nx/.env
          echo CLIENT_ID=\"${{ secrets.NAVIGRAPH_CLIENT_ID }}\" >> fbw-a32nx/.env
          echo CLIENT_SECRET=\"${{ secrets.NAVIGRAPH_CLIENT_SECRET }}\" >> fbw-a32nx/.env
          echo CHARTFOX_SECRET=\"${{ secrets.CHARTFOX_SECRET }}\" >> fbw-a32nx/.env
          echo SENTRY_DSN=\"${{ secrets.SENTRY_DSN }}\" >> fbw-a32nx/.env
          echo AIRCRAFT_PROJECT_PREFIX=${{ env.AIRCRAFT_PROJECT_PREFIX }} >> fbw-a32nx/.env
          echo AIRCRAFT_VARIANT=${{ env.AIRCRAFT_VARIANT }} >> fbw-a32nx/.env
          echo BUILD_DIR_NAME=${{ env.BUILD_DIR_NAME }} >> .env
          echo LOCALAZY_READ_KEY=${{ secrets.LOCALAZY_READ_KEY }} >> .env
          echo VITE_BUILD=false >> .env
      - name: Install dependencies
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh --clean
      - name: Build A32NX
        run: |
          ./scripts/dev-env/run.sh ./scripts/build_a32nx.sh --no-tty -j 4
          rm -rf fbw-a32nx/src
          docker system prune -af
      - name: Build ZIP files
        run: |
          df -h
          node ./scripts/fragment_a32nx.js
          cp ./fbw-a32nx/out/build-modules/modules.json ./fbw-a32nx/out/flybywire-aircraft-a320-neo/install.json
          node ./scripts/install-source_a32nx.js
          mkdir ./${{ env.BUILD_DIR_NAME }}
          cd ./fbw-a32nx/out/
          7z a -t7z -m0=lzma2 -mx=7 ../../${{ env.BUILD_DIR_NAME }}/${{ env.MASTER_ZIP_NAME }} ./flybywire-aircraft-a320-neo/
          cd ../../

      - name: Upload to CloudFlare CDN
        env:
          CLOUDFLARE_BUCKET_PASSWORD: ${{ secrets.CLOUDFLARE_BUCKET_PASSWORD }}
          CDN_BUCKET_DESTINATION: addons/a32nx/a380x-experimental
        run: |
          ./scripts/cf-cdn.sh $CDN_BUCKET_DESTINATION ./fbw-a32nx/out/build-modules

  build_a380x:
    name: Build and deploy A380X
    # Prevent running this on forks
    if: github.repository_owner == 'flybywiresim'
    runs-on: ubuntu-latest
    env:
      FBW_PRODUCTION_BUILD: 1
      BUILD_DIR_NAME: a380x-experimental-a380x
      AIRCRAFT_PROJECT_PREFIX: a380x
      AIRCRAFT_VARIANT: a380-842
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Create .env file
        run: |
          echo FBW_PRODUCTION_BUILD=1 >> fbw-a380x/.env
          echo CLIENT_ID=\"${{ secrets.NAVIGRAPH_CLIENT_ID }}\" >> fbw-a380x/.env
          echo CLIENT_SECRET=\"${{ secrets.NAVIGRAPH_CLIENT_SECRET }}\" >> fbw-a380x/.env
          echo CHARTFOX_SECRET=\"${{ secrets.CHARTFOX_SECRET }}\" >> fbw-a380x/.env
          echo SENTRY_DSN=\"${{ secrets.SENTRY_DSN }}\" >> fbw-a380x/.env
          echo AIRCRAFT_PROJECT_PREFIX=${{ env.AIRCRAFT_PROJECT_PREFIX }} >> fbw-a380x/.env
          echo AIRCRAFT_VARIANT=${{ env.AIRCRAFT_VARIANT }} >> fbw-a380x/.env
          echo BUILD_DIR_NAME=${{ env.BUILD_DIR_NAME }} >> .env
          echo LOCALAZY_READ_KEY=${{ secrets.LOCALAZY_READ_KEY }} >> .env
          echo VITE_BUILD=false >> .env
      - name: Install dependencies
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh --clean
      - name: Build A380X
        run: |
          ./scripts/dev-env/run.sh ./scripts/build_a380x.sh --no-tty -j 4
          rm -rf fbw-a380x/src
          docker system prune -af
      - name: Build ZIP files
        run: |
          df -h
          node ./scripts/fragment_a380x.js
          cp ./fbw-a380x/out/build-modules/modules.json ./fbw-a380x/out/flybywire-aircraft-a380-842/install.json
          node ./scripts/install-source_a380x.js
          mkdir ./${{ env.BUILD_DIR_NAME }}
          cd ./fbw-a380x/out/
          7z a -t7z -m0=lzma2 -mx=7 ../../${{ env.BUILD_DIR_NAME }}/${{ env.MASTER_ZIP_NAME }} ./flybywire-aircraft-a380-842/
          cd ../../

      - name: Upload to CloudFlare CDN
        env:
          CLOUDFLARE_BUCKET_PASSWORD: ${{ secrets.CLOUDFLARE_BUCKET_PASSWORD }}
          CDN_BUCKET_DESTINATION: addons/a380x/a380x-experimental
        run: |
          ./scripts/cf-cdn.sh $CDN_BUCKET_DESTINATION ./fbw-a380x/out/build-modules
